server:
  port: 9999

spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://ec2-54-73-22-169.eu-west-1.compute.amazonaws.com:5432/da8mk3ds0ehle9
    username: "{cipher}AQCU+FZf0mj6VyqNGzJyCwB7J4ZZQ9j4Y0fn9mtbuezMwPn36GUbu0H037RWJ6cZ/jNfYRKVHcNSXvLLqEsFga+0wnBOX2kXNh/qXwh6mav3+4WB5IqqX8EmeSvNpAAtgvGZ/BSmM++o20/KZVupVGTvotWRIRnmd2MZXCkRJMHIul2o0myIRctm74Wwkb1cK9s4d7nYRfhoB90Hb25PX7Vz3UMDDCg88zbIGeqLpdehU/dDucp/A7I+uVQRL8sq32jB7Rq9vhB4ncFcv8R3LpSyqLwtGn3bQqzWEcTGfLmztcWI9ZDOI774eoly+Z3sj2DzUn1ahuQsusxo7VYTMJhwCl30W8/QQjZU49SxVUiAR2k51mkkVhswZZ46VwxnVCE="
    password: "{cipher}AQCkNAF11p5TYp3FRbwwtcJdRavGM0IPhx18ljlEhUmre3SmHBy3m2Bl7IOI3b2fZEbouZA2X0igePAlj+/l2qfgGGO40DeXx4kbqNSLj1XGUOcOx4Hm70YY8Xvm5/t9rUOfEQL4tpCt24UyPB03tOGmn3jkTYihh5N4FpmBC1m9lUi0YQqaX5G7/I77b129tQgnxrrvyltU2eOjzG364X2JTOpDPmzHorg7ysOWw8pE+kCkg/kh0n5r+e+A6L3QKNdXNTElWtQLXYC02gVkOhSJrbZgaezODjthDW54w7kVMVWLnpulBTVn/nC70sktwfMKMU5lXOQXtM65XLU+kvo/f+WPgP6AOk2yzCpSR9t+Tp2lyoD9Bg0NeWBcsgBfwz61c6xU5Bxq59IUyHdowZC7R+LqxK8bexJdapJZf3SvbHgzxRvBL5C0uQwQV5JGeIDtMTZ7cEFPO0dDxtT5ELdv"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: "{cipher}AQC4/X8dAgIkahrcrP2wEUAyG8Gq8RLL+FGpii/EQNW/eeq6+Hw695gv6yk39FPf8pwInCbwfLZRA2tFbATF53ox0C5B62eGPwtv9YUdSiA4ayw6zmRE0zV3KmWGyd184h99kYcse8LjCPGAnu69Ym/1KFe9oXDHy/oYHuh7KrRm+SMiGDLgcevAF+qfm4/SNbx1qE2QbNj1KifvHfhmOQe172sra87koOqSJONpK9xTXzNnxvHdBOR3F368gOBMmQoQaBuD4GACxnbHRV5VxzHQAX+RCeMfRd+xwX3hMZGeAq7tiSRR27fUQC4ufjh1RBhqw9cP5ncfm4191sxJ3hl/wc5Dw2piYAfRfz+KMa6b8dJbPv/2HXg96NsBWF0tOsHFbAqCXKg5lGkeoMLJggyy"
    password: "{cipher}AQAHcoxSc/qbNB4IasoUWzCRGy7SS3KaJNKkmNfhOW3AZ+tZurPDpkesYm8eDdRFpcD2PwOOP32NXVgOtj68MGgJB85CtWUuTmheC852fTHePS6EG0CpC83+90aAPndbrzxRaFnhYwxvluNZbuO08efGhywxZ8tD6CyC1wRr5QLQ7hX+Ouv4Xhj+e7wXq6cKWgL4GuRjDHDEe3u5bE4sk8M8FeH0re97FSIcw999mGJhMkeJFUAc3P+mhwZEFtKOTY87qRb5OvRJmX675MSTZFpSRBvWwcpk3U7Uhwh8b/UsfvqrFx4LZok1tdTbwpREPTpgSxNUYV21Z11XkBc5r2xvp+Wy8QlgrLW9x5Q66TEML/8W5sf6y/0i0bre8IIrwwigcGR7c9naYtBqYyEJJnp2"
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com

springdoc:
  api-docs:
    path: /authentication-service/api-docs

secret:
  key: "{cipher}AQCa9l1Zs2yhPiSfjIU9PYqGoXkuvSnfJhHdpa4pwnfg3AtKzNI4PCWHRTp+rNYk5sqHJY300XlYcWD2WAO5ONDoPAQbR/i+WN5+nMljv407rxMtyn8Fa/0e9ICII/OS9vB7x1l4kE0OKKBEJiEkdcbDQS+JfdJqRBV5HiQFQrjLpG525VddRkCbcW046Z1XlWQOaOrdDNP3hC8BWW8d+0AYTFdpIFrAeYQxpRf3dJWbEK2aUjxZUbHbgXlUiFkFhtaq22FpjKK9Vkl+TLhl1K0wTc54wPQD1Szb1Ap8UZRR5Vi1OArOCIRWeJvAKw5ktZmgKbBjfI34ba5m7VbiSrVDHBZxExNmk5mFK8nNx+vznMPOwcAn6sMRuXin4SPSbsUpvDAzR0hxJcfWnodxRMGWeFu76ctfykTTcxtmU0j7bVqYKK0ewTArATnR68PtF+4lCnaYHLMl99AxWNfza806"
